version: '3'

services:
  db:
    image: postgres:11.8
    container_name: postgres_app
    environment:
      POSTGRES_DB: "escola"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"